config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :books

  root 'home#index'

  get 'tags/:tag', to: 'books#index', as: :tag
end

app/models/book.rb
class Book < ActiveRecord::Base
	mount_uploader :picture, PictureUploader

	validates :name, :description, :presence => true
  	validates :price, :numericality => { :greater_than_or_equal_to => 0.0 }
  	validates :legal, :original, inclusion: { in: [true, false] }
  	# validates :picture, presence: true
  	

  	belongs_to :owner, :class_name => "User", :foreign_key => :user_id

  	acts_as_taggable # Alias for acts_as_taggable_on :tags

  	def editable_by?(user)
		user && user == owner
	end

	def self.search(search)
	  	if search
	    	where('name LIKE ?', "%#{search}%")
	  	else
	    	all
	  	end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books

  devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :search_not_in_index, only: [:new, :edit, :show]
  helper_method :sort_column, :sort_direction, :search_not_in_index

  # GET /books
  # GET /books.json
  def index
    if params[:tag]
      @books = Book.tagged_with(params[:tag]).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 8, :page => params[:page])
    else
      @books = Book.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 8, :page => params[:page])
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find_by(id: params[:id])
    if @book.nil?
      @books = Book.all
      flash.now[:alert] = "您要找的書籍不存在。"
      render "index"
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @book = current_user.books.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: '恭喜！已成功建立書籍。' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    @book = current_user.books.find(params[:id])
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: '更新成功！' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = current_user.books.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: '書籍已成功刪除。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :description, :picture, :price, :course, :tag_list, :legal, :original)
    end

    def sort_column
      Book.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end

    def search_not_in_index
      if params[:search].present?
        redirect_to :action => 'index', :search => params[:search]
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :search, only: [:index]

	def index		
	end

	private 

	def search
      if params[:search].present?
        redirect_to :controller => 'books', :action => 'index', :search => params[:search]
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice_message
    alert_types = { :notice => :success, :alert => :danger }

    close_button_options = { :class => "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, :class => alert_class)
    end

    alerts.join("\n").html_safe
  end

  def contact_dev
    mail_to( "chi.chun_chen@icloud.com",
                 "任何建議",
                 :subject => "資財二手書-建議",
                 :encode => "javascript" )
  end

  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

app/helpers/books_helper.rb
module BooksHelper
	def order_mail book
		user = find_seller(book)
		mail_to( user.email,
                 image_tag("email-icon.png", :width => 30),
                 :subject => "資財二手書-#{book.name}",
                 :encode => "javascript" )
	end

	def find_seller book
		User.find(book.user_id)	
	end

	def same_seller? book
		current_user && book.editable_by?(current_user)	
	end

	def description_length
		35
	end

	def more_description? book
		book.description.length > description_length
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= form_for(@book) do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-inputs">

      <br>
      <%= f.text_field :name, :class => "form-control", :placeholder => "書籍名稱與版本。" %>
      
      <br>
      <%= f.text_field :price, :class => "form-control", :placeholder => "價格，請填入純數字。" %>
      
      <br>
      <%= f.select :legal, [['正版', true], ['印刷品', false]], {}, :prompt => "正版 / 印刷品", :class => "form-control" %>&nbsp;&nbsp;
      <%= f.select :original, [['原文', true], ['中文', false]], {}, :prompt => "原文 / 中文", :class => "form-control" %>
      <br>

      <br>
      <%= 
        f.text_area :description, :class => "form-control", :rows => 5, :placeholder => "物品狀況，例如：幾成新, 有無筆記等等。"
      %>

      <br>
      <%= f.label :tag_list, "選擇種類" %>
      <%= f.select :tag_list, options_for_select(ActsAsTaggableOn::Tag.all), {}, {:multiple => false, :class => "form-control"} %>

      <hr>
      <%= f.label :picture, "上傳圖片" %><br>
      <%= f.file_field :picture %>
    </div>
    
    <hr>
    <div class="form-actions">
      <%= f.submit "確定", :class => "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<h1 class="text-center"> 修改書籍資料 </h1>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="row">
  <%= render "common/tag_bar" %>

  <div class="col-md-10">
    <div class="group">
      <%= link_to '全部書籍', books_path, :class => "btn btn-default" %>
      <%= link_to '我要賣書', new_book_path, :class => "btn btn-primary pull-right" %>
    </div>
    <%= render "common/books_table" %>
    <br>
  </div>
</div>
<center>
  <%= will_paginate @books, previous_label: "上一頁", next_label: "下一頁",renderer: BootstrapPagination::Rails %>
</center>

app/views/books/new.html.erb
<h2 class="text-center"> 新增書籍 </h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">

  <%= render "common/tag_bar" %>

  <div class="col-md-4 text-center">
    <br>
    <%= image_tag(@book.picture_url, :width => 350) if @book.picture.present? %>
  </div>

  <div class="col-md-5">
    <%= render "common/book_content" %>
  </div>
</div>
<hr>

app/views/common/_book_content.html.erb
<h1>
  <b><%= @book.name %>&nbsp;</b>
  <small class="text-danger">
    <% if @book.legal %> 正版 <% else %> 印刷品 <% end %>
    <% if @book.original %> 原文 <% else %> 中文 <% end %>
  </small>
</h1>

<h4>
	賣家：<%= find_seller(@book).name %><br><br>
	<% unless same_seller?(@book) %>
  	聯絡方式：
    <%= order_mail(@book) %>
    <%= render "common/fb_send" %>
  <% else %>
    <%= link_to '更新', edit_book_path(@book), :class => "btn btn-warning" %>
  <% end %>
</h4>

<h4 class="lead">
  <%= simple_format(@book.description) %>
</h4>

<h3 class="text-danger">
  <%= number_to_currency(@book.price) %>
</h3>

<h4>
  看看同種類書籍：<%= raw @book.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
</h4>

app/views/common/_books_table.html.erb
<table class="table table-hover">
      <thead> 
        <tr>
          <th> 排序： 
          <%= sortable "name", "書名" %>
          / 
          <%= sortable "price", "價格" %>
          </th>
          <th> </th>
          <th> 種類 </th>
          <th> <%= sortable "created_at", "上架時間" %> </th>
          <th> 賣家 </th>

          <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
        <% @books.each do |book| %>
        <tr>
          <!-- 名稱/價格 -->
          <td class="col-md-3">
            <h4><%= link_to book.name, book_path(book) %></h4>
            <i> &nbsp;<%= number_to_currency(book.price) %> </i>
            <br><br>
            <%= truncate(strip_tags(book.description), :length => description_length) %>
            <% if book.description.length > description_length %>
              <%= link_to "更多", book_path(book) %>
            <% end %>
          </td>
  
          <!-- 圖片 -->          
          <td class="col-md-2">
            <%= link_to image_tag(book.picture_url, :width => 120), book_path(book) if book.picture.present? %>
          </td>
 
          <!-- tag -->
          <td class="col-md-2">
            <h4>
              <%= raw book.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
            <br><br>
            <div class="text-danger">
              <% if book.legal %> 正版 <% else %> 印刷 <% end %>&nbsp;
              <% if book.original %> 原文 <% else %> 中文 <% end %>
            </div>
            </h4>
          </td>
          
          <!-- time -->
          <td>
            <em> <%= book.created_at %> </em>
          </td>
          
          <!-- other -->
          <td>
            <% unless same_seller?(book) %>
            <h4><%= find_seller(book).name %></h4>
                <%= order_mail(book) %>&nbsp;
                <%= render "common/fb_send" %>

            <% else %>
                <%= link_to("更新", 
                            edit_book_path(book), 
                            :class => "btn btn-sm btn-default")%>

                <%= link_to("下架", 
                            book_path(book), 
                            :class => "btn btn-sm btn-default", 
                            :method=>:delete,
                            data: { confirm: "Are you sure?" } )%>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
</table>

app/views/common/_fb_send.html.erb
<div class="fb-send" data-href="https://developers.facebook.com/docs/plugins/" data-colorscheme="dark"></div>

app/views/common/_footer.html.erb
<footer>
    <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <div class="navbar-collapse collapse" id="footer-body">
                <ul class="nav navbar-nav">
                    <li>
                    	<a href="https://github.com/chichunchen/IFM">
                    		開放原始碼
                    	</a>
                    </li>
                    <li>
                    	<a href="https://github.com/chichunchen">關於開發者</a>
                    </li>
                    <li>
                    	<%= contact_dev %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">資財系二手書</a>
      <a class="navbar-brand" href="/books">
        <small>買書</small>
      </a>
      <a class="navbar-brand" href="/books/new">
        <small>賣書</small>
      </a>
      <form class="navbar-form navbar-left" role="search">
        <%= form_tag books_path, :method => 'get' do %>
          <%= hidden_field_tag :direction, params[:direction] %>
          <%= hidden_field_tag :sort, params[:sort] %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], :placeholder => "搜尋書名", :class => "form-control" %>
              <%= submit_tag "提交", :name => nil, :class => "btn btn-default" %>
            </div>
        <% end %>
      </form>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
        <li> 
          <%= link_to "臉書登入", user_omniauth_authorize_path(:facebook) %>
        </li>
        <li> <%= link_to("註冊", new_user_registration_path) %> </li>
        <li> <%= link_to("登入", new_user_session_path) %> </li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Hi!, <%= current_user.name %>  
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to("帳號設定", edit_user_registration_path )%></li>
            <li> <%= link_to("登出", destroy_user_session_path, 
                               :method => :delete ) %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/common/_tag_bar.html.erb
<div class="col-md-2">
    <div id="tag_cloud">
      <div class="list-group">

        <span href="#" class="list-group-item active">
            種類
            <span class="pull-right" id="slide-submenu">
                數量<i class="fa fa-times"></i>
            </span>
        </span>
        <% tag_cloud Book.tag_counts, %w[s m l] do |tag, css_class| %>
          <p class="list-group-item">
              <%= link_to tag.name, tag_path(tag.name), class: css_class %> <span class="badge"><%= tag.count %></span>
          </p>
        <% end %>
      </div>
    </div>
</div>

app/views/home/index.html.erb
<div class="col-md-4 col-md-offset-4">
  
  <h1 class="text-center">
  	資財系二手書
  </h1>
  <br>

  <%= render 'layouts/social_section', :title => "I wanna share IFM", :url => "https://www.facebook.com/games/ifmbooks/?fbs=-1&preview=1&locale=zh_TW" %>

  <hr>
  <div class="form-inputs">
  	<% unless user_signed_in? %>
	  	<%= button_to '臉書登入', user_omniauth_authorize_path(:facebook), :class => "btn btn-info btn-lg btn-block", :method => 'get' %>
	  	<br>
	  	<%= button_to '登入', new_user_session_path ,:class => "btn btn-warning btn-lg btn-block", :method => 'get' %>
  	<% else -%>
	  	<%= button_to("買書", books_path, :class => "btn btn-success btn-lg btn-block", :method => 'get') %>
	  	<br>
	  	<%= button_to("賣書", new_book_path, :class => "btn btn-info btn-lg btn-block", :method => 'get') %>
	<% end %>
  </div>

  <hr>
  <div class="panel panel-warning">
	  <div class="panel-heading">
	    <h3 class="panel-title">下一步</h3>
	  </div>
	  <div class="panel-body">
	    增加兩張描述用圖片(optional)
	  </div>
	</div>
  <hr>

</div>

app/views/layouts/_fb_plugin.html.erb
<!-- facebook comment -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=697573106999159&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

<!-- facebook like button -->
<div id="fb-root"></div>
  <script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%=OORConstant.facebook_app_id%>";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));
  </script>

<!-- facebook send message -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=697573106999159&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_social_section.html.erb
<div class="oor-social-buttons">
	<div class="facebook-like">
		<div class="fb-like" data-href="<%=url%>" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>資財二手書</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://apis.google.com/js/plusone.js" %>
  <%= csrf_meta_tags %>
</head>

  <%= render "common/navbar" %>

<body>
  <div class="container">
    <%= notice_message  %>
    <%= yield %>
    <%= render "layouts/fb_plugin" %>

  </div>
	<%= render "common/footer" %>

</body>
</html>